App/app.py
# Importation de Flask et des Blueprints depuis les modules des routes
from flask import Flask
from routes.main_routes import main_bp

# Création d'une application Flask
app = Flask(__name__)

# Enregistrement le blueprint dans l'application Flask
app.register_blueprint(main_bp)

# Exécution de l'application si elle est directement exécutée
if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)

App/routes/main_routes.py
# Importation du Blueprint, de render_template
from flask import Blueprint, render_template, request, redirect
# import du connecteur mongo/python
from pymongo import MongoClient
### import du module os pour la gestion de variable d'environement
import os
import re

# Création d'un objet Blueprint nommé 'main_bp' avec un préfixe d'URL '/'
main_bp = Blueprint('main', __name__, url_prefix='/')

# Informations de connexion à MongoDB
mongo_host = os.getenv('MONGO_HOST', 'localhost')
mongo_port = int(os.getenv('MONGO_PORT', 27017))
mongo_db = os.getenv('MONGO_DB', 'devops')
mongo_collection = os.getenv('MONGO_COLLECTION', 'users')
mongo_username = os.getenv('MONGO_USERNAME', 'root')
mongo_password = os.getenv('MONGO_PASSWORD', 'test1234')

# Créez l'URI de connexion à MongoDB avec le nom d'utilisateur et le mot de passe
uri = f"mongodb://{mongo_username}:{mongo_password}@{mongo_host}:{mongo_port}"

# Connexion à la base de données MongoDB
client = MongoClient(uri)
# Sélection de la base de données
db = client[mongo_db]
# Sélection de la collection
collection = db[mongo_collection]

@main_bp.route('/', methods=['GET'])
def read_user():
    """
    URL '/' avec la méthode GET
    Récupère les données de la collection users.
    Exclut le champ _id.
    Retourne les données des utilisateurs.
    """
    users = collection.find({}, {'_id': False})
    return render_template('index.html', users=users)
    return render_template('index.html', users=users)
   
    return redirect('/')

# Créer un foncion de validation d'email

def validate_email(email):
    """
    Valide l'adresse e-mail en utilisant une regex.
    Retourne True si l'e-mail est valide, False sinon.
    """
    emailRegex = r'^[\w\.-]+@[\w\.-]+\.\w+$'

    return bool(re.match(emailRegex, email))

@main_bp.route('/add-user', methods=['POST'])
def add_user():
    """
    URL '/add_user' avec la méthode POST
    Récupération des données du formulaire
    Retourne un message d'erreur et le code 40 si e-mail invalide
    """
    first_name = request.form['first_name']
    last_name = request.form['last_name']
    age = int(request.form['age'])
    email = request.form['email']

# Ajouter l'appel à la fonction

    if not validate_email(email):
        return {'error': 'Email invalide'}, 400

    """
    Insertion du nouvel utilisateur dans la collection
    Redirection vers la page d'accueil après l'ajout de l'utilisateur
    """
    user_data = {'firstName': first_name, 'lastName': last_name, 'age': age, 'email': email}
    collection.insert_one(user_data)

    return redirect('/')

App/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Utilisateurs</title>
</head>
<body>

    <h2>Liste des utilisateurs</h2>
    <table>
        <thead>
            <tr>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Âge</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.firstName }}</td>
                <td>{{ user.lastName }}</td>
                <td>{{ user.age }}</td>
                <td>{{ user.email }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

<!-- Début du code à insérer -->

    <h2>Ajouter un nouvel utilisateur</h2>
    <form method="post" action="{{ url_for('main.add_user') }}">
        <label for="first_name">Prénom:</label><br>
        <input type="text" id="first_name" name="first_name"><br>
        <label for="last_name">Nom:</label><br>
        <input type="text" id="last_name" name="last_name"><br>
        <label for="age">Age:</label><br>
        <input type="number" id="age" name="age"><br>
        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email"><br><br>
        <input type="submit" value="Ajouter">
    </form>

<!-- Fin du code à insérer -->

</body>
</html>